/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AreYouSure: typeof import('./src/components/AreYouSure.vue')['default']
    copy: typeof import('./src/components/Login copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoadingScreen: typeof import('./src/components/LoadingScreen.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Password: typeof import('./src/components/Password.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    WeatherDetails: typeof import('./src/components/WeatherDetails.vue')['default']
  }
}
